<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    public function run()
    {
        Category::insert([

            ['name'=> 'general' ],
            ['name'=> 'entertainment' ],
            ['name'=> 'arts' ],
            ['name'=> 'automobiles' ],
            ['name'=> 'books/review' ],
            ['name'=> 'business' ],
            ['name'=> 'fashion' ],
            ['name'=> 'food' ],
            ['name'=> 'health' ],
            ['name'=> 'home' ],
            ['name'=> 'insider' ],
            ['name'=> 'magazine' ],
            ['name'=> 'movies' ],
            ['name'=> 'obituaries' ],
            ['name'=> 'opinion' ],
            ['name'=> 'politics' ],
            ['name'=> 'realestate' ],
            ['name'=> 'science' ],
            ['name'=> 'sports' ],
            ['name'=> 'sundayreview' ],
            ['name'=> 'technology' ],
            ['name'=> 'theater' ],
            ['name'=> 't-magazine' ],
            ['name'=> 'travel' ],
            ['name'=> 'upshot' ],
            ['name'=> 'world' ],


            ['name'=> 'animals-farmed' ],
            ['name'=> 'artanddesign' ],
            ['name'=> 'australia-news' ],
            ['name'=> 'better-business' ],
            ['name'=> 'books' ],
            ['name'=> 'business-to-business' ],
            ['name'=> 'cardiff' ],
            ['name'=> 'childrens-books-site' ],
            ['name'=> 'cities' ],
            ['name'=> 'commentisfree' ],
            ['name'=> 'community' ],
            ['name'=> 'crosswords' ],
            ['name'=> 'culture' ],
            ['name'=> 'culture-network' ],
            ['name'=> 'culture-professionals-network' ],
            ['name'=> 'edinburgh' ],
            ['name'=> 'education' ],
            ['name'=> 'enterprise-network' ],
            ['name'=> 'environment' ],
            ['name'=> 'extra' ],
            ['name'=> 'film' ],
            ['name'=> 'football' ],
            ['name'=> 'games' ],
            ['name'=> 'global-development' ],
            ['name'=> 'global-development-professionals-network' ],
            ['name'=> 'government-computing-network' ],
            ['name'=> 'guardian-foundation' ],
            ['name'=> 'guardian-professional' ],
            ['name'=> 'healthcare-network' ],
            ['name'=> 'help' ],
            ['name'=> 'higher-education-network' ],
            ['name'=> 'housing-network' ],
            ['name'=> 'inequality' ],
            ['name'=> 'info' ],
            ['name'=> 'jobsadvice' ],
            ['name'=> 'katine' ],
            ['name'=> 'law' ],
            ['name'=> 'leeds' ],
            ['name'=> 'lifeandstyle' ],
            ['name'=> 'local' ],
            ['name'=> 'local-government-network' ],
            ['name'=> 'media' ],
            ['name'=> 'media-network' ],
            ['name'=> 'membership' ],
            ['name'=> 'money' ],
            ['name'=> 'music' ],
            ['name'=> 'news' ],
            ['name'=> 'public-leaders-network' ],
            ['name'=> 'search' ],
            ['name'=> 'small-business-network' ],
            ['name'=> 'social-care-network' ],
            ['name'=> 'social-enterprise-network' ],
            ['name'=> 'society' ],
            ['name'=> 'society-professionals' ],
            ['name'=> 'sport' ],
            ['name'=> 'stage' ],
            ['name'=> 'teacher-network' ],
            ['name'=> 'theguardian' ],
            ['name'=> 'theobserver' ],
            ['name'=> 'travel/offers' ],
            ['name'=> 'tv-and-radio' ],
            ['name'=> 'uk-news' ],
            ['name'=> 'us-news' ],
            ['name'=> 'us-wellness' ],
            ['name'=> 'voluntary-sector-network' ],
            ['name'=> 'weather' ],
            ['name'=> 'wellness' ],
            ['name'=> 'women-in-leadership' ],
            ['name'=> 'working-in-development' ],
        ]);
    }
}
